### ISSUE TITLE
Logo Design For FindFood

### ISSUE THREAD

**Issue by zularizal** [andrew-db/FindFood#9]
Hi @andrew1094 ,  I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by andrew-db** [comment]
@zularizal Very cool! I'm curious to what you had in mind for a logo versus the sample I came up with. 😎

**Comment by zularizal** [comment]
Hi @andrew-db , thank you for waiting. Here are some of my logo designs for your project. Which one do you like?

If there is something you want to change, let me know.

![rect1618](https://user-images.githubusercontent.com/38547278/58539717-1f787e00-8222-11e9-8b89-4c13ed8567b5.png)
